[package]
name = "btc_lending_project"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.13.2"
openzeppelin = "2.0.0"
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib", branch = "main" }

[dev-dependencies]
snforge_std = "0.52.0"
assert_macros = "2.13.2"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
